package pe.oh29oh29.myweb.model;

public class AttachedFileKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attached_files.IDX
	 * @mbg.generated  Wed Apr 25 13:55:15 KST 2018
	 */
	private String idx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attached_files.POST_IDX
	 * @mbg.generated  Wed Apr 25 13:55:15 KST 2018
	 */
	private String postIdx;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attached_files.IDX
	 * @return  the value of attached_files.IDX
	 * @mbg.generated  Wed Apr 25 13:55:15 KST 2018
	 */
	public String getIdx() {
		return idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attached_files.IDX
	 * @param idx  the value for attached_files.IDX
	 * @mbg.generated  Wed Apr 25 13:55:15 KST 2018
	 */
	public void setIdx(String idx) {
		this.idx = idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attached_files.POST_IDX
	 * @return  the value of attached_files.POST_IDX
	 * @mbg.generated  Wed Apr 25 13:55:15 KST 2018
	 */
	public String getPostIdx() {
		return postIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attached_files.POST_IDX
	 * @param postIdx  the value for attached_files.POST_IDX
	 * @mbg.generated  Wed Apr 25 13:55:15 KST 2018
	 */
	public void setPostIdx(String postIdx) {
		this.postIdx = postIdx;
	}
}