package pe.oh29oh29.myweb.model;

public class Categories {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CATEGORIES.IDX
	 * @mbg.generated  Wed Apr 04 16:57:34 KST 2018
	 */
	private String idx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CATEGORIES.PARENT_IDX
	 * @mbg.generated  Wed Apr 04 16:57:34 KST 2018
	 */
	private String parentIdx;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CATEGORIES.IDX
	 * @return  the value of CATEGORIES.IDX
	 * @mbg.generated  Wed Apr 04 16:57:34 KST 2018
	 */
	public String getIdx() {
		return idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CATEGORIES.IDX
	 * @param idx  the value for CATEGORIES.IDX
	 * @mbg.generated  Wed Apr 04 16:57:34 KST 2018
	 */
	public void setIdx(String idx) {
		this.idx = idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CATEGORIES.PARENT_IDX
	 * @return  the value of CATEGORIES.PARENT_IDX
	 * @mbg.generated  Wed Apr 04 16:57:34 KST 2018
	 */
	public String getParentIdx() {
		return parentIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CATEGORIES.PARENT_IDX
	 * @param parentIdx  the value for CATEGORIES.PARENT_IDX
	 * @mbg.generated  Wed Apr 04 16:57:34 KST 2018
	 */
	public void setParentIdx(String parentIdx) {
		this.parentIdx = parentIdx;
	}
}