package pe.oh29oh29.myweb.model;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATEGORIES.IDX
     *
     * @mbg.generated Tue Apr 10 19:37:22 KST 2018
     */
    private String idx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATEGORIES.PARENT_IDX
     *
     * @mbg.generated Tue Apr 10 19:37:22 KST 2018
     */
    private String parentIdx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATEGORIES.NAME
     *
     * @mbg.generated Tue Apr 10 19:37:22 KST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATEGORIES.ORD
     *
     * @mbg.generated Tue Apr 10 19:37:22 KST 2018
     */
    private Integer ord;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATEGORIES.IDX
     *
     * @return the value of CATEGORIES.IDX
     *
     * @mbg.generated Tue Apr 10 19:37:22 KST 2018
     */
    public String getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATEGORIES.IDX
     *
     * @param idx the value for CATEGORIES.IDX
     *
     * @mbg.generated Tue Apr 10 19:37:22 KST 2018
     */
    public void setIdx(String idx) {
        this.idx = idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATEGORIES.PARENT_IDX
     *
     * @return the value of CATEGORIES.PARENT_IDX
     *
     * @mbg.generated Tue Apr 10 19:37:22 KST 2018
     */
    public String getParentIdx() {
        return parentIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATEGORIES.PARENT_IDX
     *
     * @param parentIdx the value for CATEGORIES.PARENT_IDX
     *
     * @mbg.generated Tue Apr 10 19:37:22 KST 2018
     */
    public void setParentIdx(String parentIdx) {
        this.parentIdx = parentIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATEGORIES.NAME
     *
     * @return the value of CATEGORIES.NAME
     *
     * @mbg.generated Tue Apr 10 19:37:22 KST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATEGORIES.NAME
     *
     * @param name the value for CATEGORIES.NAME
     *
     * @mbg.generated Tue Apr 10 19:37:22 KST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATEGORIES.ORD
     *
     * @return the value of CATEGORIES.ORD
     *
     * @mbg.generated Tue Apr 10 19:37:22 KST 2018
     */
    public Integer getOrd() {
        return ord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATEGORIES.ORD
     *
     * @param ord the value for CATEGORIES.ORD
     *
     * @mbg.generated Tue Apr 10 19:37:22 KST 2018
     */
    public void setOrd(Integer ord) {
        this.ord = ord;
    }
}