package pe.oh29oh29.myweb.model;

public class Categories {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column categories.IDX
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	private String idx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column categories.PARENT_IDX
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	private String parentIdx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column categories.NAME
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column categories.ORDER
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	private Integer order;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column categories.IDX
	 * @return  the value of categories.IDX
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	public String getIdx() {
		return idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column categories.IDX
	 * @param idx  the value for categories.IDX
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	public void setIdx(String idx) {
		this.idx = idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column categories.PARENT_IDX
	 * @return  the value of categories.PARENT_IDX
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	public String getParentIdx() {
		return parentIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column categories.PARENT_IDX
	 * @param parentIdx  the value for categories.PARENT_IDX
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	public void setParentIdx(String parentIdx) {
		this.parentIdx = parentIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column categories.NAME
	 * @return  the value of categories.NAME
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column categories.NAME
	 * @param name  the value for categories.NAME
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column categories.ORDER
	 * @return  the value of categories.ORDER
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	public Integer getOrder() {
		return order;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column categories.ORDER
	 * @param order  the value for categories.ORDER
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	public void setOrder(Integer order) {
		this.order = order;
	}
}