package pe.oh29oh29.myweb.model;

public class Categories {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.IDX
     *
     * @mbg.generated Wed Apr 04 15:40:39 KST 2018
     */
    private String idx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.PARENT_IDX
     *
     * @mbg.generated Wed Apr 04 15:40:39 KST 2018
     */
    private String parentIdx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.IDX
     *
     * @return the value of categories.IDX
     *
     * @mbg.generated Wed Apr 04 15:40:39 KST 2018
     */
    public String getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.IDX
     *
     * @param idx the value for categories.IDX
     *
     * @mbg.generated Wed Apr 04 15:40:39 KST 2018
     */
    public void setIdx(String idx) {
        this.idx = idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.PARENT_IDX
     *
     * @return the value of categories.PARENT_IDX
     *
     * @mbg.generated Wed Apr 04 15:40:39 KST 2018
     */
    public String getParentIdx() {
        return parentIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.PARENT_IDX
     *
     * @param parentIdx the value for categories.PARENT_IDX
     *
     * @mbg.generated Wed Apr 04 15:40:39 KST 2018
     */
    public void setParentIdx(String parentIdx) {
        this.parentIdx = parentIdx;
    }
}