package pe.oh29oh29.myweb.model;

public class Category {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column categories.IDX
	 * @mbg.generated  Wed Apr 25 13:55:15 KST 2018
	 */
	private String idx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column categories.PARENT_IDX
	 * @mbg.generated  Wed Apr 25 13:55:15 KST 2018
	 */
	private String parentIdx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column categories.NAME
	 * @mbg.generated  Wed Apr 25 13:55:15 KST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column categories.DEPTH
	 * @mbg.generated  Wed Apr 25 13:55:15 KST 2018
	 */
	private Integer depth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column categories.ORD
	 * @mbg.generated  Wed Apr 25 13:55:15 KST 2018
	 */
	private Integer ord;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column categories.IS_PRIVATE
	 * @mbg.generated  Wed Apr 25 13:55:15 KST 2018
	 */
	private Integer isPrivate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column categories.IDX
	 * @return  the value of categories.IDX
	 * @mbg.generated  Wed Apr 25 13:55:15 KST 2018
	 */
	public String getIdx() {
		return idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column categories.IDX
	 * @param idx  the value for categories.IDX
	 * @mbg.generated  Wed Apr 25 13:55:15 KST 2018
	 */
	public void setIdx(String idx) {
		this.idx = idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column categories.PARENT_IDX
	 * @return  the value of categories.PARENT_IDX
	 * @mbg.generated  Wed Apr 25 13:55:15 KST 2018
	 */
	public String getParentIdx() {
		return parentIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column categories.PARENT_IDX
	 * @param parentIdx  the value for categories.PARENT_IDX
	 * @mbg.generated  Wed Apr 25 13:55:15 KST 2018
	 */
	public void setParentIdx(String parentIdx) {
		this.parentIdx = parentIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column categories.NAME
	 * @return  the value of categories.NAME
	 * @mbg.generated  Wed Apr 25 13:55:15 KST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column categories.NAME
	 * @param name  the value for categories.NAME
	 * @mbg.generated  Wed Apr 25 13:55:15 KST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column categories.DEPTH
	 * @return  the value of categories.DEPTH
	 * @mbg.generated  Wed Apr 25 13:55:15 KST 2018
	 */
	public Integer getDepth() {
		return depth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column categories.DEPTH
	 * @param depth  the value for categories.DEPTH
	 * @mbg.generated  Wed Apr 25 13:55:15 KST 2018
	 */
	public void setDepth(Integer depth) {
		this.depth = depth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column categories.ORD
	 * @return  the value of categories.ORD
	 * @mbg.generated  Wed Apr 25 13:55:15 KST 2018
	 */
	public Integer getOrd() {
		return ord;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column categories.ORD
	 * @param ord  the value for categories.ORD
	 * @mbg.generated  Wed Apr 25 13:55:15 KST 2018
	 */
	public void setOrd(Integer ord) {
		this.ord = ord;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column categories.IS_PRIVATE
	 * @return  the value of categories.IS_PRIVATE
	 * @mbg.generated  Wed Apr 25 13:55:15 KST 2018
	 */
	public Integer getIsPrivate() {
		return isPrivate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column categories.IS_PRIVATE
	 * @param isPrivate  the value for categories.IS_PRIVATE
	 * @mbg.generated  Wed Apr 25 13:55:15 KST 2018
	 */
	public void setIsPrivate(Integer isPrivate) {
		this.isPrivate = isPrivate;
	}
}