package pe.oh29oh29.myweb.model;

public class CommentKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.IDX
     *
     * @mbg.generated Wed Apr 11 19:49:13 KST 2018
     */
    private String idx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.POST_IDX
     *
     * @mbg.generated Wed Apr 11 19:49:13 KST 2018
     */
    private String postIdx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.MEMBER_IDX
     *
     * @mbg.generated Wed Apr 11 19:49:13 KST 2018
     */
    private String memberIdx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.IDX
     *
     * @return the value of comments.IDX
     *
     * @mbg.generated Wed Apr 11 19:49:13 KST 2018
     */
    public String getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.IDX
     *
     * @param idx the value for comments.IDX
     *
     * @mbg.generated Wed Apr 11 19:49:13 KST 2018
     */
    public void setIdx(String idx) {
        this.idx = idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.POST_IDX
     *
     * @return the value of comments.POST_IDX
     *
     * @mbg.generated Wed Apr 11 19:49:13 KST 2018
     */
    public String getPostIdx() {
        return postIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.POST_IDX
     *
     * @param postIdx the value for comments.POST_IDX
     *
     * @mbg.generated Wed Apr 11 19:49:13 KST 2018
     */
    public void setPostIdx(String postIdx) {
        this.postIdx = postIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.MEMBER_IDX
     *
     * @return the value of comments.MEMBER_IDX
     *
     * @mbg.generated Wed Apr 11 19:49:13 KST 2018
     */
    public String getMemberIdx() {
        return memberIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.MEMBER_IDX
     *
     * @param memberIdx the value for comments.MEMBER_IDX
     *
     * @mbg.generated Wed Apr 11 19:49:13 KST 2018
     */
    public void setMemberIdx(String memberIdx) {
        this.memberIdx = memberIdx;
    }
}