package pe.oh29oh29.myweb.model;

import java.util.ArrayList;
import java.util.List;

public class FileStoreExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table file_stores
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table file_stores
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table file_stores
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_stores
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	public FileStoreExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_stores
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_stores
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_stores
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_stores
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_stores
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_stores
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_stores
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_stores
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_stores
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_stores
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table file_stores
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdxIsNull() {
			addCriterion("IDX is null");
			return (Criteria) this;
		}

		public Criteria andIdxIsNotNull() {
			addCriterion("IDX is not null");
			return (Criteria) this;
		}

		public Criteria andIdxEqualTo(String value) {
			addCriterion("IDX =", value, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxNotEqualTo(String value) {
			addCriterion("IDX <>", value, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxGreaterThan(String value) {
			addCriterion("IDX >", value, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxGreaterThanOrEqualTo(String value) {
			addCriterion("IDX >=", value, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxLessThan(String value) {
			addCriterion("IDX <", value, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxLessThanOrEqualTo(String value) {
			addCriterion("IDX <=", value, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxLike(String value) {
			addCriterion("IDX like", value, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxNotLike(String value) {
			addCriterion("IDX not like", value, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxIn(List<String> values) {
			addCriterion("IDX in", values, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxNotIn(List<String> values) {
			addCriterion("IDX not in", values, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxBetween(String value1, String value2) {
			addCriterion("IDX between", value1, value2, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxNotBetween(String value1, String value2) {
			addCriterion("IDX not between", value1, value2, "idx");
			return (Criteria) this;
		}

		public Criteria andContextPathIsNull() {
			addCriterion("CONTEXT_PATH is null");
			return (Criteria) this;
		}

		public Criteria andContextPathIsNotNull() {
			addCriterion("CONTEXT_PATH is not null");
			return (Criteria) this;
		}

		public Criteria andContextPathEqualTo(String value) {
			addCriterion("CONTEXT_PATH =", value, "contextPath");
			return (Criteria) this;
		}

		public Criteria andContextPathNotEqualTo(String value) {
			addCriterion("CONTEXT_PATH <>", value, "contextPath");
			return (Criteria) this;
		}

		public Criteria andContextPathGreaterThan(String value) {
			addCriterion("CONTEXT_PATH >", value, "contextPath");
			return (Criteria) this;
		}

		public Criteria andContextPathGreaterThanOrEqualTo(String value) {
			addCriterion("CONTEXT_PATH >=", value, "contextPath");
			return (Criteria) this;
		}

		public Criteria andContextPathLessThan(String value) {
			addCriterion("CONTEXT_PATH <", value, "contextPath");
			return (Criteria) this;
		}

		public Criteria andContextPathLessThanOrEqualTo(String value) {
			addCriterion("CONTEXT_PATH <=", value, "contextPath");
			return (Criteria) this;
		}

		public Criteria andContextPathLike(String value) {
			addCriterion("CONTEXT_PATH like", value, "contextPath");
			return (Criteria) this;
		}

		public Criteria andContextPathNotLike(String value) {
			addCriterion("CONTEXT_PATH not like", value, "contextPath");
			return (Criteria) this;
		}

		public Criteria andContextPathIn(List<String> values) {
			addCriterion("CONTEXT_PATH in", values, "contextPath");
			return (Criteria) this;
		}

		public Criteria andContextPathNotIn(List<String> values) {
			addCriterion("CONTEXT_PATH not in", values, "contextPath");
			return (Criteria) this;
		}

		public Criteria andContextPathBetween(String value1, String value2) {
			addCriterion("CONTEXT_PATH between", value1, value2, "contextPath");
			return (Criteria) this;
		}

		public Criteria andContextPathNotBetween(String value1, String value2) {
			addCriterion("CONTEXT_PATH not between", value1, value2, "contextPath");
			return (Criteria) this;
		}

		public Criteria andRealPathIsNull() {
			addCriterion("REAL_PATH is null");
			return (Criteria) this;
		}

		public Criteria andRealPathIsNotNull() {
			addCriterion("REAL_PATH is not null");
			return (Criteria) this;
		}

		public Criteria andRealPathEqualTo(String value) {
			addCriterion("REAL_PATH =", value, "realPath");
			return (Criteria) this;
		}

		public Criteria andRealPathNotEqualTo(String value) {
			addCriterion("REAL_PATH <>", value, "realPath");
			return (Criteria) this;
		}

		public Criteria andRealPathGreaterThan(String value) {
			addCriterion("REAL_PATH >", value, "realPath");
			return (Criteria) this;
		}

		public Criteria andRealPathGreaterThanOrEqualTo(String value) {
			addCriterion("REAL_PATH >=", value, "realPath");
			return (Criteria) this;
		}

		public Criteria andRealPathLessThan(String value) {
			addCriterion("REAL_PATH <", value, "realPath");
			return (Criteria) this;
		}

		public Criteria andRealPathLessThanOrEqualTo(String value) {
			addCriterion("REAL_PATH <=", value, "realPath");
			return (Criteria) this;
		}

		public Criteria andRealPathLike(String value) {
			addCriterion("REAL_PATH like", value, "realPath");
			return (Criteria) this;
		}

		public Criteria andRealPathNotLike(String value) {
			addCriterion("REAL_PATH not like", value, "realPath");
			return (Criteria) this;
		}

		public Criteria andRealPathIn(List<String> values) {
			addCriterion("REAL_PATH in", values, "realPath");
			return (Criteria) this;
		}

		public Criteria andRealPathNotIn(List<String> values) {
			addCriterion("REAL_PATH not in", values, "realPath");
			return (Criteria) this;
		}

		public Criteria andRealPathBetween(String value1, String value2) {
			addCriterion("REAL_PATH between", value1, value2, "realPath");
			return (Criteria) this;
		}

		public Criteria andRealPathNotBetween(String value1, String value2) {
			addCriterion("REAL_PATH not between", value1, value2, "realPath");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("TYPE is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(Integer value) {
			addCriterion("TYPE =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(Integer value) {
			addCriterion("TYPE <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(Integer value) {
			addCriterion("TYPE >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("TYPE >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(Integer value) {
			addCriterion("TYPE <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(Integer value) {
			addCriterion("TYPE <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<Integer> values) {
			addCriterion("TYPE in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<Integer> values) {
			addCriterion("TYPE not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(Integer value1, Integer value2) {
			addCriterion("TYPE between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("TYPE not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andOrdIsNull() {
			addCriterion("ORD is null");
			return (Criteria) this;
		}

		public Criteria andOrdIsNotNull() {
			addCriterion("ORD is not null");
			return (Criteria) this;
		}

		public Criteria andOrdEqualTo(Integer value) {
			addCriterion("ORD =", value, "ord");
			return (Criteria) this;
		}

		public Criteria andOrdNotEqualTo(Integer value) {
			addCriterion("ORD <>", value, "ord");
			return (Criteria) this;
		}

		public Criteria andOrdGreaterThan(Integer value) {
			addCriterion("ORD >", value, "ord");
			return (Criteria) this;
		}

		public Criteria andOrdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ORD >=", value, "ord");
			return (Criteria) this;
		}

		public Criteria andOrdLessThan(Integer value) {
			addCriterion("ORD <", value, "ord");
			return (Criteria) this;
		}

		public Criteria andOrdLessThanOrEqualTo(Integer value) {
			addCriterion("ORD <=", value, "ord");
			return (Criteria) this;
		}

		public Criteria andOrdIn(List<Integer> values) {
			addCriterion("ORD in", values, "ord");
			return (Criteria) this;
		}

		public Criteria andOrdNotIn(List<Integer> values) {
			addCriterion("ORD not in", values, "ord");
			return (Criteria) this;
		}

		public Criteria andOrdBetween(Integer value1, Integer value2) {
			addCriterion("ORD between", value1, value2, "ord");
			return (Criteria) this;
		}

		public Criteria andOrdNotBetween(Integer value1, Integer value2) {
			addCriterion("ORD not between", value1, value2, "ord");
			return (Criteria) this;
		}

		public Criteria andAvailableIsNull() {
			addCriterion("AVAILABLE is null");
			return (Criteria) this;
		}

		public Criteria andAvailableIsNotNull() {
			addCriterion("AVAILABLE is not null");
			return (Criteria) this;
		}

		public Criteria andAvailableEqualTo(Integer value) {
			addCriterion("AVAILABLE =", value, "available");
			return (Criteria) this;
		}

		public Criteria andAvailableNotEqualTo(Integer value) {
			addCriterion("AVAILABLE <>", value, "available");
			return (Criteria) this;
		}

		public Criteria andAvailableGreaterThan(Integer value) {
			addCriterion("AVAILABLE >", value, "available");
			return (Criteria) this;
		}

		public Criteria andAvailableGreaterThanOrEqualTo(Integer value) {
			addCriterion("AVAILABLE >=", value, "available");
			return (Criteria) this;
		}

		public Criteria andAvailableLessThan(Integer value) {
			addCriterion("AVAILABLE <", value, "available");
			return (Criteria) this;
		}

		public Criteria andAvailableLessThanOrEqualTo(Integer value) {
			addCriterion("AVAILABLE <=", value, "available");
			return (Criteria) this;
		}

		public Criteria andAvailableIn(List<Integer> values) {
			addCriterion("AVAILABLE in", values, "available");
			return (Criteria) this;
		}

		public Criteria andAvailableNotIn(List<Integer> values) {
			addCriterion("AVAILABLE not in", values, "available");
			return (Criteria) this;
		}

		public Criteria andAvailableBetween(Integer value1, Integer value2) {
			addCriterion("AVAILABLE between", value1, value2, "available");
			return (Criteria) this;
		}

		public Criteria andAvailableNotBetween(Integer value1, Integer value2) {
			addCriterion("AVAILABLE not between", value1, value2, "available");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table file_stores
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table file_store
     *
     * @mbg.generated do_not_delete_during_merge Tue Apr 24 23:45:06 KST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}