package pe.oh29oh29.myweb.model;

public class FileStore {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column file_stores.IDX
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	private String idx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column file_stores.CONTEXT_PATH
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	private String contextPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column file_stores.REAL_PATH
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	private String realPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column file_stores.TYPE
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column file_stores.ORD
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	private Integer ord;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column file_stores.AVAILABLE
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	private Integer available;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column file_stores.IDX
	 * @return  the value of file_stores.IDX
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	public String getIdx() {
		return idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column file_stores.IDX
	 * @param idx  the value for file_stores.IDX
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	public void setIdx(String idx) {
		this.idx = idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column file_stores.CONTEXT_PATH
	 * @return  the value of file_stores.CONTEXT_PATH
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	public String getContextPath() {
		return contextPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column file_stores.CONTEXT_PATH
	 * @param contextPath  the value for file_stores.CONTEXT_PATH
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	public void setContextPath(String contextPath) {
		this.contextPath = contextPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column file_stores.REAL_PATH
	 * @return  the value of file_stores.REAL_PATH
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	public String getRealPath() {
		return realPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column file_stores.REAL_PATH
	 * @param realPath  the value for file_stores.REAL_PATH
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	public void setRealPath(String realPath) {
		this.realPath = realPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column file_stores.TYPE
	 * @return  the value of file_stores.TYPE
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column file_stores.TYPE
	 * @param type  the value for file_stores.TYPE
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column file_stores.ORD
	 * @return  the value of file_stores.ORD
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	public Integer getOrd() {
		return ord;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column file_stores.ORD
	 * @param ord  the value for file_stores.ORD
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	public void setOrd(Integer ord) {
		this.ord = ord;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column file_stores.AVAILABLE
	 * @return  the value of file_stores.AVAILABLE
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	public Integer getAvailable() {
		return available;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column file_stores.AVAILABLE
	 * @param available  the value for file_stores.AVAILABLE
	 * @mbg.generated  Mon May 14 19:04:42 KST 2018
	 */
	public void setAvailable(Integer available) {
		this.available = available;
	}
}