package pe.oh29oh29.myweb.model;

public class Member {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members.IDX
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	private String idx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members.ID
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members.NAME
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members.EMAIL
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members.IS_ADMIN
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	private Integer isAdmin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members.PROVIDER
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	private String provider;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members.REG_DATE
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	private String regDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members.IS_EXIT
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	private Integer isExit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members.EXIT_DATE
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	private String exitDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members.IDX
	 * @return  the value of members.IDX
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	public String getIdx() {
		return idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members.IDX
	 * @param idx  the value for members.IDX
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	public void setIdx(String idx) {
		this.idx = idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members.ID
	 * @return  the value of members.ID
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members.ID
	 * @param id  the value for members.ID
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members.NAME
	 * @return  the value of members.NAME
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members.NAME
	 * @param name  the value for members.NAME
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members.EMAIL
	 * @return  the value of members.EMAIL
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members.EMAIL
	 * @param email  the value for members.EMAIL
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members.IS_ADMIN
	 * @return  the value of members.IS_ADMIN
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	public Integer getIsAdmin() {
		return isAdmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members.IS_ADMIN
	 * @param isAdmin  the value for members.IS_ADMIN
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	public void setIsAdmin(Integer isAdmin) {
		this.isAdmin = isAdmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members.PROVIDER
	 * @return  the value of members.PROVIDER
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	public String getProvider() {
		return provider;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members.PROVIDER
	 * @param provider  the value for members.PROVIDER
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	public void setProvider(String provider) {
		this.provider = provider;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members.REG_DATE
	 * @return  the value of members.REG_DATE
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	public String getRegDate() {
		return regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members.REG_DATE
	 * @param regDate  the value for members.REG_DATE
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	public void setRegDate(String regDate) {
		this.regDate = regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members.IS_EXIT
	 * @return  the value of members.IS_EXIT
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	public Integer getIsExit() {
		return isExit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members.IS_EXIT
	 * @param isExit  the value for members.IS_EXIT
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	public void setIsExit(Integer isExit) {
		this.isExit = isExit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members.EXIT_DATE
	 * @return  the value of members.EXIT_DATE
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	public String getExitDate() {
		return exitDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members.EXIT_DATE
	 * @param exitDate  the value for members.EXIT_DATE
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	public void setExitDate(String exitDate) {
		this.exitDate = exitDate;
	}
}