package pe.oh29oh29.myweb.model;

public class Members {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEMBERS.IDX
	 * @mbg.generated  Wed Apr 04 16:57:34 KST 2018
	 */
	private String idx;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEMBERS.IDX
	 * @return  the value of MEMBERS.IDX
	 * @mbg.generated  Wed Apr 04 16:57:34 KST 2018
	 */
	public String getIdx() {
		return idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEMBERS.IDX
	 * @param idx  the value for MEMBERS.IDX
	 * @mbg.generated  Wed Apr 04 16:57:34 KST 2018
	 */
	public void setIdx(String idx) {
		this.idx = idx;
	}
}