package pe.oh29oh29.myweb.model;

public class Member {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEMBERS.IDX
	 * @mbg.generated  Tue Apr 10 19:37:22 KST 2018
	 */
	private String idx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEMBERS.ID
	 * @mbg.generated  Tue Apr 10 19:37:22 KST 2018
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEMBERS.PASSWD
	 * @mbg.generated  Tue Apr 10 19:37:22 KST 2018
	 */
	private String passwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEMBERS.NAME
	 * @mbg.generated  Tue Apr 10 19:37:22 KST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEMBERS.EMAIL
	 * @mbg.generated  Tue Apr 10 19:37:22 KST 2018
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEMBERS.IS_EXIT
	 * @mbg.generated  Tue Apr 10 19:37:22 KST 2018
	 */
	private Integer isExit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEMBERS.REG_DATE
	 * @mbg.generated  Tue Apr 10 19:37:22 KST 2018
	 */
	private String regDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEMBERS.IDX
	 * @return  the value of MEMBERS.IDX
	 * @mbg.generated  Tue Apr 10 19:37:22 KST 2018
	 */
	public String getIdx() {
		return idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEMBERS.IDX
	 * @param idx  the value for MEMBERS.IDX
	 * @mbg.generated  Tue Apr 10 19:37:22 KST 2018
	 */
	public void setIdx(String idx) {
		this.idx = idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEMBERS.ID
	 * @return  the value of MEMBERS.ID
	 * @mbg.generated  Tue Apr 10 19:37:22 KST 2018
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEMBERS.ID
	 * @param id  the value for MEMBERS.ID
	 * @mbg.generated  Tue Apr 10 19:37:22 KST 2018
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEMBERS.PASSWD
	 * @return  the value of MEMBERS.PASSWD
	 * @mbg.generated  Tue Apr 10 19:37:22 KST 2018
	 */
	public String getPasswd() {
		return passwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEMBERS.PASSWD
	 * @param passwd  the value for MEMBERS.PASSWD
	 * @mbg.generated  Tue Apr 10 19:37:22 KST 2018
	 */
	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEMBERS.NAME
	 * @return  the value of MEMBERS.NAME
	 * @mbg.generated  Tue Apr 10 19:37:22 KST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEMBERS.NAME
	 * @param name  the value for MEMBERS.NAME
	 * @mbg.generated  Tue Apr 10 19:37:22 KST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEMBERS.EMAIL
	 * @return  the value of MEMBERS.EMAIL
	 * @mbg.generated  Tue Apr 10 19:37:22 KST 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEMBERS.EMAIL
	 * @param email  the value for MEMBERS.EMAIL
	 * @mbg.generated  Tue Apr 10 19:37:22 KST 2018
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEMBERS.IS_EXIT
	 * @return  the value of MEMBERS.IS_EXIT
	 * @mbg.generated  Tue Apr 10 19:37:22 KST 2018
	 */
	public Integer getIsExit() {
		return isExit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEMBERS.IS_EXIT
	 * @param isExit  the value for MEMBERS.IS_EXIT
	 * @mbg.generated  Tue Apr 10 19:37:22 KST 2018
	 */
	public void setIsExit(Integer isExit) {
		this.isExit = isExit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEMBERS.REG_DATE
	 * @return  the value of MEMBERS.REG_DATE
	 * @mbg.generated  Tue Apr 10 19:37:22 KST 2018
	 */
	public String getRegDate() {
		return regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEMBERS.REG_DATE
	 * @param regDate  the value for MEMBERS.REG_DATE
	 * @mbg.generated  Tue Apr 10 19:37:22 KST 2018
	 */
	public void setRegDate(String regDate) {
		this.regDate = regDate;
	}
}