package pe.oh29oh29.myweb.model;

public class Members {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members.IDX
     *
     * @mbg.generated Wed Apr 04 15:40:39 KST 2018
     */
    private String idx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members.IDX
     *
     * @return the value of members.IDX
     *
     * @mbg.generated Wed Apr 04 15:40:39 KST 2018
     */
    public String getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members.IDX
     *
     * @param idx the value for members.IDX
     *
     * @mbg.generated Wed Apr 04 15:40:39 KST 2018
     */
    public void setIdx(String idx) {
        this.idx = idx;
    }
}