package pe.oh29oh29.myweb.model;

public class Post extends PostKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts.TITLE
	 * @mbg.generated  Thu Apr 26 10:05:58 KST 2018
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts.DESCRIPTION
	 * @mbg.generated  Thu Apr 26 10:05:58 KST 2018
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts.REG_DATE
	 * @mbg.generated  Thu Apr 26 10:05:58 KST 2018
	 */
	private String regDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts.CONTENTS
	 * @mbg.generated  Thu Apr 26 10:05:58 KST 2018
	 */
	private String contents;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts.TITLE
	 * @return  the value of posts.TITLE
	 * @mbg.generated  Thu Apr 26 10:05:58 KST 2018
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts.TITLE
	 * @param title  the value for posts.TITLE
	 * @mbg.generated  Thu Apr 26 10:05:58 KST 2018
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts.DESCRIPTION
	 * @return  the value of posts.DESCRIPTION
	 * @mbg.generated  Thu Apr 26 10:05:58 KST 2018
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts.DESCRIPTION
	 * @param description  the value for posts.DESCRIPTION
	 * @mbg.generated  Thu Apr 26 10:05:58 KST 2018
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts.REG_DATE
	 * @return  the value of posts.REG_DATE
	 * @mbg.generated  Thu Apr 26 10:05:58 KST 2018
	 */
	public String getRegDate() {
		return regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts.REG_DATE
	 * @param regDate  the value for posts.REG_DATE
	 * @mbg.generated  Thu Apr 26 10:05:58 KST 2018
	 */
	public void setRegDate(String regDate) {
		this.regDate = regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts.CONTENTS
	 * @return  the value of posts.CONTENTS
	 * @mbg.generated  Thu Apr 26 10:05:58 KST 2018
	 */
	public String getContents() {
		return contents;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts.CONTENTS
	 * @param contents  the value for posts.CONTENTS
	 * @mbg.generated  Thu Apr 26 10:05:58 KST 2018
	 */
	public void setContents(String contents) {
		this.contents = contents;
	}
}