package pe.oh29oh29.myweb.model;

public class PostCommentsKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_comments.IDX
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	private String idx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_comments.POST_IDX
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	private String postIdx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_comments.MEMBER_IDX
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	private String memberIdx;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_comments.IDX
	 * @return  the value of post_comments.IDX
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	public String getIdx() {
		return idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_comments.IDX
	 * @param idx  the value for post_comments.IDX
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	public void setIdx(String idx) {
		this.idx = idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_comments.POST_IDX
	 * @return  the value of post_comments.POST_IDX
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	public String getPostIdx() {
		return postIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_comments.POST_IDX
	 * @param postIdx  the value for post_comments.POST_IDX
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	public void setPostIdx(String postIdx) {
		this.postIdx = postIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_comments.MEMBER_IDX
	 * @return  the value of post_comments.MEMBER_IDX
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	public String getMemberIdx() {
		return memberIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_comments.MEMBER_IDX
	 * @param memberIdx  the value for post_comments.MEMBER_IDX
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	public void setMemberIdx(String memberIdx) {
		this.memberIdx = memberIdx;
	}
}