package pe.oh29oh29.myweb.model;

public class PostView {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts_view.POST_IDX
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	private String postIdx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts_view.CATEGORY
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	private String category;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts_view.TITLE
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts_view.DESCRIPTION
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts_view.WRITER
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	private String writer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts_view.REG_DATE
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	private String regDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts_view.CONTENTS
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	private String contents;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts_view.POST_IDX
	 * @return  the value of posts_view.POST_IDX
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	public String getPostIdx() {
		return postIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts_view.POST_IDX
	 * @param postIdx  the value for posts_view.POST_IDX
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	public void setPostIdx(String postIdx) {
		this.postIdx = postIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts_view.CATEGORY
	 * @return  the value of posts_view.CATEGORY
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	public String getCategory() {
		return category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts_view.CATEGORY
	 * @param category  the value for posts_view.CATEGORY
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	public void setCategory(String category) {
		this.category = category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts_view.TITLE
	 * @return  the value of posts_view.TITLE
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts_view.TITLE
	 * @param title  the value for posts_view.TITLE
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts_view.DESCRIPTION
	 * @return  the value of posts_view.DESCRIPTION
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts_view.DESCRIPTION
	 * @param description  the value for posts_view.DESCRIPTION
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts_view.WRITER
	 * @return  the value of posts_view.WRITER
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	public String getWriter() {
		return writer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts_view.WRITER
	 * @param writer  the value for posts_view.WRITER
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	public void setWriter(String writer) {
		this.writer = writer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts_view.REG_DATE
	 * @return  the value of posts_view.REG_DATE
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	public String getRegDate() {
		return regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts_view.REG_DATE
	 * @param regDate  the value for posts_view.REG_DATE
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	public void setRegDate(String regDate) {
		this.regDate = regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts_view.CONTENTS
	 * @return  the value of posts_view.CONTENTS
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	public String getContents() {
		return contents;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts_view.CONTENTS
	 * @param contents  the value for posts_view.CONTENTS
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	public void setContents(String contents) {
		this.contents = contents;
	}
}