package pe.oh29oh29.myweb.model;

import java.util.ArrayList;
import java.util.List;

public class PostCommentsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table post_comments
     *
     * @mbg.generated Wed Apr 04 15:40:39 KST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table post_comments
     *
     * @mbg.generated Wed Apr 04 15:40:39 KST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table post_comments
     *
     * @mbg.generated Wed Apr 04 15:40:39 KST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comments
     *
     * @mbg.generated Wed Apr 04 15:40:39 KST 2018
     */
    public PostCommentsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comments
     *
     * @mbg.generated Wed Apr 04 15:40:39 KST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comments
     *
     * @mbg.generated Wed Apr 04 15:40:39 KST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comments
     *
     * @mbg.generated Wed Apr 04 15:40:39 KST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comments
     *
     * @mbg.generated Wed Apr 04 15:40:39 KST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comments
     *
     * @mbg.generated Wed Apr 04 15:40:39 KST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comments
     *
     * @mbg.generated Wed Apr 04 15:40:39 KST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comments
     *
     * @mbg.generated Wed Apr 04 15:40:39 KST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comments
     *
     * @mbg.generated Wed Apr 04 15:40:39 KST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comments
     *
     * @mbg.generated Wed Apr 04 15:40:39 KST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comments
     *
     * @mbg.generated Wed Apr 04 15:40:39 KST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table post_comments
     *
     * @mbg.generated Wed Apr 04 15:40:39 KST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdxIsNull() {
            addCriterion("IDX is null");
            return (Criteria) this;
        }

        public Criteria andIdxIsNotNull() {
            addCriterion("IDX is not null");
            return (Criteria) this;
        }

        public Criteria andIdxEqualTo(String value) {
            addCriterion("IDX =", value, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxNotEqualTo(String value) {
            addCriterion("IDX <>", value, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxGreaterThan(String value) {
            addCriterion("IDX >", value, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxGreaterThanOrEqualTo(String value) {
            addCriterion("IDX >=", value, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxLessThan(String value) {
            addCriterion("IDX <", value, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxLessThanOrEqualTo(String value) {
            addCriterion("IDX <=", value, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxLike(String value) {
            addCriterion("IDX like", value, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxNotLike(String value) {
            addCriterion("IDX not like", value, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxIn(List<String> values) {
            addCriterion("IDX in", values, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxNotIn(List<String> values) {
            addCriterion("IDX not in", values, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxBetween(String value1, String value2) {
            addCriterion("IDX between", value1, value2, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxNotBetween(String value1, String value2) {
            addCriterion("IDX not between", value1, value2, "idx");
            return (Criteria) this;
        }

        public Criteria andPostIdxIsNull() {
            addCriterion("POST_IDX is null");
            return (Criteria) this;
        }

        public Criteria andPostIdxIsNotNull() {
            addCriterion("POST_IDX is not null");
            return (Criteria) this;
        }

        public Criteria andPostIdxEqualTo(String value) {
            addCriterion("POST_IDX =", value, "postIdx");
            return (Criteria) this;
        }

        public Criteria andPostIdxNotEqualTo(String value) {
            addCriterion("POST_IDX <>", value, "postIdx");
            return (Criteria) this;
        }

        public Criteria andPostIdxGreaterThan(String value) {
            addCriterion("POST_IDX >", value, "postIdx");
            return (Criteria) this;
        }

        public Criteria andPostIdxGreaterThanOrEqualTo(String value) {
            addCriterion("POST_IDX >=", value, "postIdx");
            return (Criteria) this;
        }

        public Criteria andPostIdxLessThan(String value) {
            addCriterion("POST_IDX <", value, "postIdx");
            return (Criteria) this;
        }

        public Criteria andPostIdxLessThanOrEqualTo(String value) {
            addCriterion("POST_IDX <=", value, "postIdx");
            return (Criteria) this;
        }

        public Criteria andPostIdxLike(String value) {
            addCriterion("POST_IDX like", value, "postIdx");
            return (Criteria) this;
        }

        public Criteria andPostIdxNotLike(String value) {
            addCriterion("POST_IDX not like", value, "postIdx");
            return (Criteria) this;
        }

        public Criteria andPostIdxIn(List<String> values) {
            addCriterion("POST_IDX in", values, "postIdx");
            return (Criteria) this;
        }

        public Criteria andPostIdxNotIn(List<String> values) {
            addCriterion("POST_IDX not in", values, "postIdx");
            return (Criteria) this;
        }

        public Criteria andPostIdxBetween(String value1, String value2) {
            addCriterion("POST_IDX between", value1, value2, "postIdx");
            return (Criteria) this;
        }

        public Criteria andPostIdxNotBetween(String value1, String value2) {
            addCriterion("POST_IDX not between", value1, value2, "postIdx");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table post_comments
     *
     * @mbg.generated do_not_delete_during_merge Wed Apr 04 15:40:39 KST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table post_comments
     *
     * @mbg.generated Wed Apr 04 15:40:39 KST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}