package pe.oh29oh29.myweb.model;

public class PostTagRelationKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POST_TAG_RELATIONS.POST_IDX
     *
     * @mbg.generated Wed May 02 16:52:57 KST 2018
     */
    private String postIdx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POST_TAG_RELATIONS.TAG_IDX
     *
     * @mbg.generated Wed May 02 16:52:57 KST 2018
     */
    private String tagIdx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POST_TAG_RELATIONS.POST_IDX
     *
     * @return the value of POST_TAG_RELATIONS.POST_IDX
     *
     * @mbg.generated Wed May 02 16:52:57 KST 2018
     */
    public String getPostIdx() {
        return postIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POST_TAG_RELATIONS.POST_IDX
     *
     * @param postIdx the value for POST_TAG_RELATIONS.POST_IDX
     *
     * @mbg.generated Wed May 02 16:52:57 KST 2018
     */
    public void setPostIdx(String postIdx) {
        this.postIdx = postIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POST_TAG_RELATIONS.TAG_IDX
     *
     * @return the value of POST_TAG_RELATIONS.TAG_IDX
     *
     * @mbg.generated Wed May 02 16:52:57 KST 2018
     */
    public String getTagIdx() {
        return tagIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POST_TAG_RELATIONS.TAG_IDX
     *
     * @param tagIdx the value for POST_TAG_RELATIONS.TAG_IDX
     *
     * @mbg.generated Wed May 02 16:52:57 KST 2018
     */
    public void setTagIdx(String tagIdx) {
        this.tagIdx = tagIdx;
    }
}