package pe.oh29oh29.myweb.model;

public class PostKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts.IDX
	 * @mbg.generated  Thu Apr 26 10:05:58 KST 2018
	 */
	private String idx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts.CATEGORY_IDX
	 * @mbg.generated  Thu Apr 26 10:05:58 KST 2018
	 */
	private String categoryIdx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts.MEMBER_IDX
	 * @mbg.generated  Thu Apr 26 10:05:58 KST 2018
	 */
	private String memberIdx;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts.IDX
	 * @return  the value of posts.IDX
	 * @mbg.generated  Thu Apr 26 10:05:58 KST 2018
	 */
	public String getIdx() {
		return idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts.IDX
	 * @param idx  the value for posts.IDX
	 * @mbg.generated  Thu Apr 26 10:05:58 KST 2018
	 */
	public void setIdx(String idx) {
		this.idx = idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts.CATEGORY_IDX
	 * @return  the value of posts.CATEGORY_IDX
	 * @mbg.generated  Thu Apr 26 10:05:58 KST 2018
	 */
	public String getCategoryIdx() {
		return categoryIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts.CATEGORY_IDX
	 * @param categoryIdx  the value for posts.CATEGORY_IDX
	 * @mbg.generated  Thu Apr 26 10:05:58 KST 2018
	 */
	public void setCategoryIdx(String categoryIdx) {
		this.categoryIdx = categoryIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts.MEMBER_IDX
	 * @return  the value of posts.MEMBER_IDX
	 * @mbg.generated  Thu Apr 26 10:05:58 KST 2018
	 */
	public String getMemberIdx() {
		return memberIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts.MEMBER_IDX
	 * @param memberIdx  the value for posts.MEMBER_IDX
	 * @mbg.generated  Thu Apr 26 10:05:58 KST 2018
	 */
	public void setMemberIdx(String memberIdx) {
		this.memberIdx = memberIdx;
	}
}