package pe.oh29oh29.myweb.model;

public class PostView {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts_view.IDX
	 * @mbg.generated  Mon Apr 30 22:29:24 KST 2018
	 */
	private String idx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts_view.TITLE
	 * @mbg.generated  Mon Apr 30 22:29:24 KST 2018
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts_view.DESCRIPTION
	 * @mbg.generated  Mon Apr 30 22:29:24 KST 2018
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts_view.REG_DATE
	 * @mbg.generated  Mon Apr 30 22:29:24 KST 2018
	 */
	private String regDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts_view.IDX
	 * @return  the value of posts_view.IDX
	 * @mbg.generated  Mon Apr 30 22:29:24 KST 2018
	 */
	public String getIdx() {
		return idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts_view.IDX
	 * @param idx  the value for posts_view.IDX
	 * @mbg.generated  Mon Apr 30 22:29:24 KST 2018
	 */
	public void setIdx(String idx) {
		this.idx = idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts_view.TITLE
	 * @return  the value of posts_view.TITLE
	 * @mbg.generated  Mon Apr 30 22:29:24 KST 2018
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts_view.TITLE
	 * @param title  the value for posts_view.TITLE
	 * @mbg.generated  Mon Apr 30 22:29:24 KST 2018
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts_view.DESCRIPTION
	 * @return  the value of posts_view.DESCRIPTION
	 * @mbg.generated  Mon Apr 30 22:29:24 KST 2018
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts_view.DESCRIPTION
	 * @param description  the value for posts_view.DESCRIPTION
	 * @mbg.generated  Mon Apr 30 22:29:24 KST 2018
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts_view.REG_DATE
	 * @return  the value of posts_view.REG_DATE
	 * @mbg.generated  Mon Apr 30 22:29:24 KST 2018
	 */
	public String getRegDate() {
		return regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts_view.REG_DATE
	 * @param regDate  the value for posts_view.REG_DATE
	 * @mbg.generated  Mon Apr 30 22:29:24 KST 2018
	 */
	public void setRegDate(String regDate) {
		this.regDate = regDate;
	}
}