package pe.oh29oh29.myweb.model;

public class PostCommentsKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column POST_COMMENTS.IDX
	 * @mbg.generated  Wed Apr 04 16:57:34 KST 2018
	 */
	private String idx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column POST_COMMENTS.POST_IDX
	 * @mbg.generated  Wed Apr 04 16:57:34 KST 2018
	 */
	private String postIdx;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column POST_COMMENTS.IDX
	 * @return  the value of POST_COMMENTS.IDX
	 * @mbg.generated  Wed Apr 04 16:57:34 KST 2018
	 */
	public String getIdx() {
		return idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column POST_COMMENTS.IDX
	 * @param idx  the value for POST_COMMENTS.IDX
	 * @mbg.generated  Wed Apr 04 16:57:34 KST 2018
	 */
	public void setIdx(String idx) {
		this.idx = idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column POST_COMMENTS.POST_IDX
	 * @return  the value of POST_COMMENTS.POST_IDX
	 * @mbg.generated  Wed Apr 04 16:57:34 KST 2018
	 */
	public String getPostIdx() {
		return postIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column POST_COMMENTS.POST_IDX
	 * @param postIdx  the value for POST_COMMENTS.POST_IDX
	 * @mbg.generated  Wed Apr 04 16:57:34 KST 2018
	 */
	public void setPostIdx(String postIdx) {
		this.postIdx = postIdx;
	}
}