package pe.oh29oh29.myweb.model;

public class PostTagRelationView {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_tag_relations_view.POST_IDX
	 * @mbg.generated  Wed May 02 17:00:00 KST 2018
	 */
	private String postIdx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_tag_relations_view.TAG_IDX
	 * @mbg.generated  Wed May 02 17:00:00 KST 2018
	 */
	private String tagIdx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_tag_relations_view.TAG_NAME
	 * @mbg.generated  Wed May 02 17:00:00 KST 2018
	 */
	private String tagName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_tag_relations_view.ORD
	 * @mbg.generated  Wed May 02 17:00:00 KST 2018
	 */
	private Integer ord;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_tag_relations_view.POST_IDX
	 * @return  the value of post_tag_relations_view.POST_IDX
	 * @mbg.generated  Wed May 02 17:00:00 KST 2018
	 */
	public String getPostIdx() {
		return postIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_tag_relations_view.POST_IDX
	 * @param postIdx  the value for post_tag_relations_view.POST_IDX
	 * @mbg.generated  Wed May 02 17:00:00 KST 2018
	 */
	public void setPostIdx(String postIdx) {
		this.postIdx = postIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_tag_relations_view.TAG_IDX
	 * @return  the value of post_tag_relations_view.TAG_IDX
	 * @mbg.generated  Wed May 02 17:00:00 KST 2018
	 */
	public String getTagIdx() {
		return tagIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_tag_relations_view.TAG_IDX
	 * @param tagIdx  the value for post_tag_relations_view.TAG_IDX
	 * @mbg.generated  Wed May 02 17:00:00 KST 2018
	 */
	public void setTagIdx(String tagIdx) {
		this.tagIdx = tagIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_tag_relations_view.TAG_NAME
	 * @return  the value of post_tag_relations_view.TAG_NAME
	 * @mbg.generated  Wed May 02 17:00:00 KST 2018
	 */
	public String getTagName() {
		return tagName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_tag_relations_view.TAG_NAME
	 * @param tagName  the value for post_tag_relations_view.TAG_NAME
	 * @mbg.generated  Wed May 02 17:00:00 KST 2018
	 */
	public void setTagName(String tagName) {
		this.tagName = tagName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_tag_relations_view.ORD
	 * @return  the value of post_tag_relations_view.ORD
	 * @mbg.generated  Wed May 02 17:00:00 KST 2018
	 */
	public Integer getOrd() {
		return ord;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_tag_relations_view.ORD
	 * @param ord  the value for post_tag_relations_view.ORD
	 * @mbg.generated  Wed May 02 17:00:00 KST 2018
	 */
	public void setOrd(Integer ord) {
		this.ord = ord;
	}
}