package pe.oh29oh29.myweb.model;

import java.util.ArrayList;
import java.util.List;

public class PostViewExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table posts_view
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table posts_view
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table posts_view
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts_view
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	public PostViewExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts_view
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts_view
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts_view
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts_view
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts_view
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts_view
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts_view
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts_view
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts_view
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts_view
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table posts_view
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andPostIdxIsNull() {
			addCriterion("POST_IDX is null");
			return (Criteria) this;
		}

		public Criteria andPostIdxIsNotNull() {
			addCriterion("POST_IDX is not null");
			return (Criteria) this;
		}

		public Criteria andPostIdxEqualTo(String value) {
			addCriterion("POST_IDX =", value, "postIdx");
			return (Criteria) this;
		}

		public Criteria andPostIdxNotEqualTo(String value) {
			addCriterion("POST_IDX <>", value, "postIdx");
			return (Criteria) this;
		}

		public Criteria andPostIdxGreaterThan(String value) {
			addCriterion("POST_IDX >", value, "postIdx");
			return (Criteria) this;
		}

		public Criteria andPostIdxGreaterThanOrEqualTo(String value) {
			addCriterion("POST_IDX >=", value, "postIdx");
			return (Criteria) this;
		}

		public Criteria andPostIdxLessThan(String value) {
			addCriterion("POST_IDX <", value, "postIdx");
			return (Criteria) this;
		}

		public Criteria andPostIdxLessThanOrEqualTo(String value) {
			addCriterion("POST_IDX <=", value, "postIdx");
			return (Criteria) this;
		}

		public Criteria andPostIdxLike(String value) {
			addCriterion("POST_IDX like", value, "postIdx");
			return (Criteria) this;
		}

		public Criteria andPostIdxNotLike(String value) {
			addCriterion("POST_IDX not like", value, "postIdx");
			return (Criteria) this;
		}

		public Criteria andPostIdxIn(List<String> values) {
			addCriterion("POST_IDX in", values, "postIdx");
			return (Criteria) this;
		}

		public Criteria andPostIdxNotIn(List<String> values) {
			addCriterion("POST_IDX not in", values, "postIdx");
			return (Criteria) this;
		}

		public Criteria andPostIdxBetween(String value1, String value2) {
			addCriterion("POST_IDX between", value1, value2, "postIdx");
			return (Criteria) this;
		}

		public Criteria andPostIdxNotBetween(String value1, String value2) {
			addCriterion("POST_IDX not between", value1, value2, "postIdx");
			return (Criteria) this;
		}

		public Criteria andCategoryIsNull() {
			addCriterion("CATEGORY is null");
			return (Criteria) this;
		}

		public Criteria andCategoryIsNotNull() {
			addCriterion("CATEGORY is not null");
			return (Criteria) this;
		}

		public Criteria andCategoryEqualTo(String value) {
			addCriterion("CATEGORY =", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryNotEqualTo(String value) {
			addCriterion("CATEGORY <>", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryGreaterThan(String value) {
			addCriterion("CATEGORY >", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryGreaterThanOrEqualTo(String value) {
			addCriterion("CATEGORY >=", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryLessThan(String value) {
			addCriterion("CATEGORY <", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryLessThanOrEqualTo(String value) {
			addCriterion("CATEGORY <=", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryLike(String value) {
			addCriterion("CATEGORY like", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryNotLike(String value) {
			addCriterion("CATEGORY not like", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryIn(List<String> values) {
			addCriterion("CATEGORY in", values, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryNotIn(List<String> values) {
			addCriterion("CATEGORY not in", values, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryBetween(String value1, String value2) {
			addCriterion("CATEGORY between", value1, value2, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryNotBetween(String value1, String value2) {
			addCriterion("CATEGORY not between", value1, value2, "category");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("TITLE is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("TITLE is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("TITLE =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("TITLE <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("TITLE >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("TITLE >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("TITLE <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("TITLE <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("TITLE like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("TITLE not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("TITLE in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("TITLE not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("TITLE between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("TITLE not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNull() {
			addCriterion("DESCRIPTION is null");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNotNull() {
			addCriterion("DESCRIPTION is not null");
			return (Criteria) this;
		}

		public Criteria andDescriptionEqualTo(String value) {
			addCriterion("DESCRIPTION =", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotEqualTo(String value) {
			addCriterion("DESCRIPTION <>", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThan(String value) {
			addCriterion("DESCRIPTION >", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("DESCRIPTION >=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThan(String value) {
			addCriterion("DESCRIPTION <", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThanOrEqualTo(String value) {
			addCriterion("DESCRIPTION <=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLike(String value) {
			addCriterion("DESCRIPTION like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotLike(String value) {
			addCriterion("DESCRIPTION not like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionIn(List<String> values) {
			addCriterion("DESCRIPTION in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotIn(List<String> values) {
			addCriterion("DESCRIPTION not in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionBetween(String value1, String value2) {
			addCriterion("DESCRIPTION between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotBetween(String value1, String value2) {
			addCriterion("DESCRIPTION not between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andWriterIsNull() {
			addCriterion("WRITER is null");
			return (Criteria) this;
		}

		public Criteria andWriterIsNotNull() {
			addCriterion("WRITER is not null");
			return (Criteria) this;
		}

		public Criteria andWriterEqualTo(String value) {
			addCriterion("WRITER =", value, "writer");
			return (Criteria) this;
		}

		public Criteria andWriterNotEqualTo(String value) {
			addCriterion("WRITER <>", value, "writer");
			return (Criteria) this;
		}

		public Criteria andWriterGreaterThan(String value) {
			addCriterion("WRITER >", value, "writer");
			return (Criteria) this;
		}

		public Criteria andWriterGreaterThanOrEqualTo(String value) {
			addCriterion("WRITER >=", value, "writer");
			return (Criteria) this;
		}

		public Criteria andWriterLessThan(String value) {
			addCriterion("WRITER <", value, "writer");
			return (Criteria) this;
		}

		public Criteria andWriterLessThanOrEqualTo(String value) {
			addCriterion("WRITER <=", value, "writer");
			return (Criteria) this;
		}

		public Criteria andWriterLike(String value) {
			addCriterion("WRITER like", value, "writer");
			return (Criteria) this;
		}

		public Criteria andWriterNotLike(String value) {
			addCriterion("WRITER not like", value, "writer");
			return (Criteria) this;
		}

		public Criteria andWriterIn(List<String> values) {
			addCriterion("WRITER in", values, "writer");
			return (Criteria) this;
		}

		public Criteria andWriterNotIn(List<String> values) {
			addCriterion("WRITER not in", values, "writer");
			return (Criteria) this;
		}

		public Criteria andWriterBetween(String value1, String value2) {
			addCriterion("WRITER between", value1, value2, "writer");
			return (Criteria) this;
		}

		public Criteria andWriterNotBetween(String value1, String value2) {
			addCriterion("WRITER not between", value1, value2, "writer");
			return (Criteria) this;
		}

		public Criteria andRegDateIsNull() {
			addCriterion("REG_DATE is null");
			return (Criteria) this;
		}

		public Criteria andRegDateIsNotNull() {
			addCriterion("REG_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andRegDateEqualTo(String value) {
			addCriterion("REG_DATE =", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateNotEqualTo(String value) {
			addCriterion("REG_DATE <>", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateGreaterThan(String value) {
			addCriterion("REG_DATE >", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateGreaterThanOrEqualTo(String value) {
			addCriterion("REG_DATE >=", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateLessThan(String value) {
			addCriterion("REG_DATE <", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateLessThanOrEqualTo(String value) {
			addCriterion("REG_DATE <=", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateLike(String value) {
			addCriterion("REG_DATE like", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateNotLike(String value) {
			addCriterion("REG_DATE not like", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateIn(List<String> values) {
			addCriterion("REG_DATE in", values, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateNotIn(List<String> values) {
			addCriterion("REG_DATE not in", values, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateBetween(String value1, String value2) {
			addCriterion("REG_DATE between", value1, value2, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateNotBetween(String value1, String value2) {
			addCriterion("REG_DATE not between", value1, value2, "regDate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table posts_view
	 * @mbg.generated  Thu Apr 26 16:57:40 KST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table posts_view
     *
     * @mbg.generated do_not_delete_during_merge Thu Apr 26 11:44:11 KST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}