package pe.oh29oh29.myweb.model;

public class Post {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts.IDX
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	private String idx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts.MEMBER_IDX
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	private String memberIdx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts.TITLE
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts.DESCRIPTION
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts.URI_ID
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	private String uriId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts.REG_DATE
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	private String regDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts.CONTENTS
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	private String contents;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts.IDX
	 * @return  the value of posts.IDX
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	public String getIdx() {
		return idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts.IDX
	 * @param idx  the value for posts.IDX
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	public void setIdx(String idx) {
		this.idx = idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts.MEMBER_IDX
	 * @return  the value of posts.MEMBER_IDX
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	public String getMemberIdx() {
		return memberIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts.MEMBER_IDX
	 * @param memberIdx  the value for posts.MEMBER_IDX
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	public void setMemberIdx(String memberIdx) {
		this.memberIdx = memberIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts.TITLE
	 * @return  the value of posts.TITLE
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts.TITLE
	 * @param title  the value for posts.TITLE
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts.DESCRIPTION
	 * @return  the value of posts.DESCRIPTION
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts.DESCRIPTION
	 * @param description  the value for posts.DESCRIPTION
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts.URI_ID
	 * @return  the value of posts.URI_ID
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	public String getUriId() {
		return uriId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts.URI_ID
	 * @param uriId  the value for posts.URI_ID
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	public void setUriId(String uriId) {
		this.uriId = uriId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts.REG_DATE
	 * @return  the value of posts.REG_DATE
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	public String getRegDate() {
		return regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts.REG_DATE
	 * @param regDate  the value for posts.REG_DATE
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	public void setRegDate(String regDate) {
		this.regDate = regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts.CONTENTS
	 * @return  the value of posts.CONTENTS
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	public String getContents() {
		return contents;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts.CONTENTS
	 * @param contents  the value for posts.CONTENTS
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	public void setContents(String contents) {
		this.contents = contents;
	}
}