package pe.oh29oh29.myweb.model;

public class PostView {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts_view.IDX
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	private String idx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts_view.TITLE
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts_view.DESCRIPTION
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts_view.URI_ID
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	private String uriId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts_view.REG_DATE
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	private String regDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts_view.CONTENTS
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	private String contents;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts_view.TAGS
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	private String tags;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts_view.IDX
	 * @return  the value of posts_view.IDX
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	public String getIdx() {
		return idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts_view.IDX
	 * @param idx  the value for posts_view.IDX
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	public void setIdx(String idx) {
		this.idx = idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts_view.TITLE
	 * @return  the value of posts_view.TITLE
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts_view.TITLE
	 * @param title  the value for posts_view.TITLE
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts_view.DESCRIPTION
	 * @return  the value of posts_view.DESCRIPTION
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts_view.DESCRIPTION
	 * @param description  the value for posts_view.DESCRIPTION
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts_view.URI_ID
	 * @return  the value of posts_view.URI_ID
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	public String getUriId() {
		return uriId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts_view.URI_ID
	 * @param uriId  the value for posts_view.URI_ID
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	public void setUriId(String uriId) {
		this.uriId = uriId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts_view.REG_DATE
	 * @return  the value of posts_view.REG_DATE
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	public String getRegDate() {
		return regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts_view.REG_DATE
	 * @param regDate  the value for posts_view.REG_DATE
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	public void setRegDate(String regDate) {
		this.regDate = regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts_view.CONTENTS
	 * @return  the value of posts_view.CONTENTS
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	public String getContents() {
		return contents;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts_view.CONTENTS
	 * @param contents  the value for posts_view.CONTENTS
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	public void setContents(String contents) {
		this.contents = contents;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts_view.TAGS
	 * @return  the value of posts_view.TAGS
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	public String getTags() {
		return tags;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts_view.TAGS
	 * @param tags  the value for posts_view.TAGS
	 * @mbg.generated  Tue May 01 17:02:37 KST 2018
	 */
	public void setTags(String tags) {
		this.tags = tags;
	}
}