package pe.oh29oh29.myweb.model;

public class PostRelationKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_relation.IDX
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	private String idx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_relation.POST_IDX
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	private String postIdx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_relation.POST_PARENT_IDX
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	private String postParentIdx;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_relation.IDX
	 * @return  the value of post_relation.IDX
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	public String getIdx() {
		return idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_relation.IDX
	 * @param idx  the value for post_relation.IDX
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	public void setIdx(String idx) {
		this.idx = idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_relation.POST_IDX
	 * @return  the value of post_relation.POST_IDX
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	public String getPostIdx() {
		return postIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_relation.POST_IDX
	 * @param postIdx  the value for post_relation.POST_IDX
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	public void setPostIdx(String postIdx) {
		this.postIdx = postIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_relation.POST_PARENT_IDX
	 * @return  the value of post_relation.POST_PARENT_IDX
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	public String getPostParentIdx() {
		return postParentIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_relation.POST_PARENT_IDX
	 * @param postParentIdx  the value for post_relation.POST_PARENT_IDX
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	public void setPostParentIdx(String postParentIdx) {
		this.postParentIdx = postParentIdx;
	}
}