package pe.oh29oh29.myweb.model;

public class PostComments extends PostCommentsKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_comments.CONTENTS
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	private String contents;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_comments.REG_DATE
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	private String regDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_comments.CONTENTS
	 * @return  the value of post_comments.CONTENTS
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	public String getContents() {
		return contents;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_comments.CONTENTS
	 * @param contents  the value for post_comments.CONTENTS
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	public void setContents(String contents) {
		this.contents = contents;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_comments.REG_DATE
	 * @return  the value of post_comments.REG_DATE
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	public String getRegDate() {
		return regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_comments.REG_DATE
	 * @param regDate  the value for post_comments.REG_DATE
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	public void setRegDate(String regDate) {
		this.regDate = regDate;
	}
}