package pe.oh29oh29.myweb.model;

public class PostComments extends PostCommentsKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column POST_COMMENTS.CONTENTS
	 * @mbg.generated  Mon Apr 09 17:44:07 KST 2018
	 */
	private String contents;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column POST_COMMENTS.REG_DATE
	 * @mbg.generated  Mon Apr 09 17:44:07 KST 2018
	 */
	private String regDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column POST_COMMENTS.CONTENTS
	 * @return  the value of POST_COMMENTS.CONTENTS
	 * @mbg.generated  Mon Apr 09 17:44:07 KST 2018
	 */
	public String getContents() {
		return contents;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column POST_COMMENTS.CONTENTS
	 * @param contents  the value for POST_COMMENTS.CONTENTS
	 * @mbg.generated  Mon Apr 09 17:44:07 KST 2018
	 */
	public void setContents(String contents) {
		this.contents = contents;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column POST_COMMENTS.REG_DATE
	 * @return  the value of POST_COMMENTS.REG_DATE
	 * @mbg.generated  Mon Apr 09 17:44:07 KST 2018
	 */
	public String getRegDate() {
		return regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column POST_COMMENTS.REG_DATE
	 * @param regDate  the value for POST_COMMENTS.REG_DATE
	 * @mbg.generated  Mon Apr 09 17:44:07 KST 2018
	 */
	public void setRegDate(String regDate) {
		this.regDate = regDate;
	}
}