package pe.oh29oh29.myweb.model;

public class PostTagRelation extends PostTagRelationKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column POST_TAG_RELATIONS.ORD
	 * @mbg.generated  Wed May 02 16:52:57 KST 2018
	 */
	private Integer ord;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column POST_TAG_RELATIONS.ORD
	 * @return  the value of POST_TAG_RELATIONS.ORD
	 * @mbg.generated  Wed May 02 16:52:57 KST 2018
	 */
	public Integer getOrd() {
		return ord;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column POST_TAG_RELATIONS.ORD
	 * @param ord  the value for POST_TAG_RELATIONS.ORD
	 * @mbg.generated  Wed May 02 16:52:57 KST 2018
	 */
	public void setOrd(Integer ord) {
		this.ord = ord;
	}
}