package pe.oh29oh29.myweb.model;

import java.util.ArrayList;
import java.util.List;

public class PostTagRelationViewExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table post_tag_relations_view
	 * @mbg.generated  Wed May 02 17:00:00 KST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table post_tag_relations_view
	 * @mbg.generated  Wed May 02 17:00:00 KST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table post_tag_relations_view
	 * @mbg.generated  Wed May 02 17:00:00 KST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_tag_relations_view
	 * @mbg.generated  Wed May 02 17:00:00 KST 2018
	 */
	public PostTagRelationViewExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_tag_relations_view
	 * @mbg.generated  Wed May 02 17:00:00 KST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_tag_relations_view
	 * @mbg.generated  Wed May 02 17:00:00 KST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_tag_relations_view
	 * @mbg.generated  Wed May 02 17:00:00 KST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_tag_relations_view
	 * @mbg.generated  Wed May 02 17:00:00 KST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_tag_relations_view
	 * @mbg.generated  Wed May 02 17:00:00 KST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_tag_relations_view
	 * @mbg.generated  Wed May 02 17:00:00 KST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_tag_relations_view
	 * @mbg.generated  Wed May 02 17:00:00 KST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_tag_relations_view
	 * @mbg.generated  Wed May 02 17:00:00 KST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_tag_relations_view
	 * @mbg.generated  Wed May 02 17:00:00 KST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_tag_relations_view
	 * @mbg.generated  Wed May 02 17:00:00 KST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table post_tag_relations_view
	 * @mbg.generated  Wed May 02 17:00:00 KST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andPostIdxIsNull() {
			addCriterion("POST_IDX is null");
			return (Criteria) this;
		}

		public Criteria andPostIdxIsNotNull() {
			addCriterion("POST_IDX is not null");
			return (Criteria) this;
		}

		public Criteria andPostIdxEqualTo(String value) {
			addCriterion("POST_IDX =", value, "postIdx");
			return (Criteria) this;
		}

		public Criteria andPostIdxNotEqualTo(String value) {
			addCriterion("POST_IDX <>", value, "postIdx");
			return (Criteria) this;
		}

		public Criteria andPostIdxGreaterThan(String value) {
			addCriterion("POST_IDX >", value, "postIdx");
			return (Criteria) this;
		}

		public Criteria andPostIdxGreaterThanOrEqualTo(String value) {
			addCriterion("POST_IDX >=", value, "postIdx");
			return (Criteria) this;
		}

		public Criteria andPostIdxLessThan(String value) {
			addCriterion("POST_IDX <", value, "postIdx");
			return (Criteria) this;
		}

		public Criteria andPostIdxLessThanOrEqualTo(String value) {
			addCriterion("POST_IDX <=", value, "postIdx");
			return (Criteria) this;
		}

		public Criteria andPostIdxLike(String value) {
			addCriterion("POST_IDX like", value, "postIdx");
			return (Criteria) this;
		}

		public Criteria andPostIdxNotLike(String value) {
			addCriterion("POST_IDX not like", value, "postIdx");
			return (Criteria) this;
		}

		public Criteria andPostIdxIn(List<String> values) {
			addCriterion("POST_IDX in", values, "postIdx");
			return (Criteria) this;
		}

		public Criteria andPostIdxNotIn(List<String> values) {
			addCriterion("POST_IDX not in", values, "postIdx");
			return (Criteria) this;
		}

		public Criteria andPostIdxBetween(String value1, String value2) {
			addCriterion("POST_IDX between", value1, value2, "postIdx");
			return (Criteria) this;
		}

		public Criteria andPostIdxNotBetween(String value1, String value2) {
			addCriterion("POST_IDX not between", value1, value2, "postIdx");
			return (Criteria) this;
		}

		public Criteria andTagIdxIsNull() {
			addCriterion("TAG_IDX is null");
			return (Criteria) this;
		}

		public Criteria andTagIdxIsNotNull() {
			addCriterion("TAG_IDX is not null");
			return (Criteria) this;
		}

		public Criteria andTagIdxEqualTo(String value) {
			addCriterion("TAG_IDX =", value, "tagIdx");
			return (Criteria) this;
		}

		public Criteria andTagIdxNotEqualTo(String value) {
			addCriterion("TAG_IDX <>", value, "tagIdx");
			return (Criteria) this;
		}

		public Criteria andTagIdxGreaterThan(String value) {
			addCriterion("TAG_IDX >", value, "tagIdx");
			return (Criteria) this;
		}

		public Criteria andTagIdxGreaterThanOrEqualTo(String value) {
			addCriterion("TAG_IDX >=", value, "tagIdx");
			return (Criteria) this;
		}

		public Criteria andTagIdxLessThan(String value) {
			addCriterion("TAG_IDX <", value, "tagIdx");
			return (Criteria) this;
		}

		public Criteria andTagIdxLessThanOrEqualTo(String value) {
			addCriterion("TAG_IDX <=", value, "tagIdx");
			return (Criteria) this;
		}

		public Criteria andTagIdxLike(String value) {
			addCriterion("TAG_IDX like", value, "tagIdx");
			return (Criteria) this;
		}

		public Criteria andTagIdxNotLike(String value) {
			addCriterion("TAG_IDX not like", value, "tagIdx");
			return (Criteria) this;
		}

		public Criteria andTagIdxIn(List<String> values) {
			addCriterion("TAG_IDX in", values, "tagIdx");
			return (Criteria) this;
		}

		public Criteria andTagIdxNotIn(List<String> values) {
			addCriterion("TAG_IDX not in", values, "tagIdx");
			return (Criteria) this;
		}

		public Criteria andTagIdxBetween(String value1, String value2) {
			addCriterion("TAG_IDX between", value1, value2, "tagIdx");
			return (Criteria) this;
		}

		public Criteria andTagIdxNotBetween(String value1, String value2) {
			addCriterion("TAG_IDX not between", value1, value2, "tagIdx");
			return (Criteria) this;
		}

		public Criteria andTagNameIsNull() {
			addCriterion("TAG_NAME is null");
			return (Criteria) this;
		}

		public Criteria andTagNameIsNotNull() {
			addCriterion("TAG_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andTagNameEqualTo(String value) {
			addCriterion("TAG_NAME =", value, "tagName");
			return (Criteria) this;
		}

		public Criteria andTagNameNotEqualTo(String value) {
			addCriterion("TAG_NAME <>", value, "tagName");
			return (Criteria) this;
		}

		public Criteria andTagNameGreaterThan(String value) {
			addCriterion("TAG_NAME >", value, "tagName");
			return (Criteria) this;
		}

		public Criteria andTagNameGreaterThanOrEqualTo(String value) {
			addCriterion("TAG_NAME >=", value, "tagName");
			return (Criteria) this;
		}

		public Criteria andTagNameLessThan(String value) {
			addCriterion("TAG_NAME <", value, "tagName");
			return (Criteria) this;
		}

		public Criteria andTagNameLessThanOrEqualTo(String value) {
			addCriterion("TAG_NAME <=", value, "tagName");
			return (Criteria) this;
		}

		public Criteria andTagNameLike(String value) {
			addCriterion("TAG_NAME like", value, "tagName");
			return (Criteria) this;
		}

		public Criteria andTagNameNotLike(String value) {
			addCriterion("TAG_NAME not like", value, "tagName");
			return (Criteria) this;
		}

		public Criteria andTagNameIn(List<String> values) {
			addCriterion("TAG_NAME in", values, "tagName");
			return (Criteria) this;
		}

		public Criteria andTagNameNotIn(List<String> values) {
			addCriterion("TAG_NAME not in", values, "tagName");
			return (Criteria) this;
		}

		public Criteria andTagNameBetween(String value1, String value2) {
			addCriterion("TAG_NAME between", value1, value2, "tagName");
			return (Criteria) this;
		}

		public Criteria andTagNameNotBetween(String value1, String value2) {
			addCriterion("TAG_NAME not between", value1, value2, "tagName");
			return (Criteria) this;
		}

		public Criteria andOrdIsNull() {
			addCriterion("ORD is null");
			return (Criteria) this;
		}

		public Criteria andOrdIsNotNull() {
			addCriterion("ORD is not null");
			return (Criteria) this;
		}

		public Criteria andOrdEqualTo(Integer value) {
			addCriterion("ORD =", value, "ord");
			return (Criteria) this;
		}

		public Criteria andOrdNotEqualTo(Integer value) {
			addCriterion("ORD <>", value, "ord");
			return (Criteria) this;
		}

		public Criteria andOrdGreaterThan(Integer value) {
			addCriterion("ORD >", value, "ord");
			return (Criteria) this;
		}

		public Criteria andOrdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ORD >=", value, "ord");
			return (Criteria) this;
		}

		public Criteria andOrdLessThan(Integer value) {
			addCriterion("ORD <", value, "ord");
			return (Criteria) this;
		}

		public Criteria andOrdLessThanOrEqualTo(Integer value) {
			addCriterion("ORD <=", value, "ord");
			return (Criteria) this;
		}

		public Criteria andOrdIn(List<Integer> values) {
			addCriterion("ORD in", values, "ord");
			return (Criteria) this;
		}

		public Criteria andOrdNotIn(List<Integer> values) {
			addCriterion("ORD not in", values, "ord");
			return (Criteria) this;
		}

		public Criteria andOrdBetween(Integer value1, Integer value2) {
			addCriterion("ORD between", value1, value2, "ord");
			return (Criteria) this;
		}

		public Criteria andOrdNotBetween(Integer value1, Integer value2) {
			addCriterion("ORD not between", value1, value2, "ord");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table post_tag_relations_view
	 * @mbg.generated  Wed May 02 17:00:00 KST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table post_tag_relations_view
     *
     * @mbg.generated do_not_delete_during_merge Wed May 02 16:59:13 KST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}