package pe.oh29oh29.myweb.model;

public class RelationKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation.IDX
     *
     * @mbg.generated Wed Apr 11 19:49:13 KST 2018
     */
    private String idx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation.POST_IDX
     *
     * @mbg.generated Wed Apr 11 19:49:13 KST 2018
     */
    private String postIdx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation.RELATED_POST_IDX
     *
     * @mbg.generated Wed Apr 11 19:49:13 KST 2018
     */
    private String relatedPostIdx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation.IDX
     *
     * @return the value of relation.IDX
     *
     * @mbg.generated Wed Apr 11 19:49:13 KST 2018
     */
    public String getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation.IDX
     *
     * @param idx the value for relation.IDX
     *
     * @mbg.generated Wed Apr 11 19:49:13 KST 2018
     */
    public void setIdx(String idx) {
        this.idx = idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation.POST_IDX
     *
     * @return the value of relation.POST_IDX
     *
     * @mbg.generated Wed Apr 11 19:49:13 KST 2018
     */
    public String getPostIdx() {
        return postIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation.POST_IDX
     *
     * @param postIdx the value for relation.POST_IDX
     *
     * @mbg.generated Wed Apr 11 19:49:13 KST 2018
     */
    public void setPostIdx(String postIdx) {
        this.postIdx = postIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation.RELATED_POST_IDX
     *
     * @return the value of relation.RELATED_POST_IDX
     *
     * @mbg.generated Wed Apr 11 19:49:13 KST 2018
     */
    public String getRelatedPostIdx() {
        return relatedPostIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation.RELATED_POST_IDX
     *
     * @param relatedPostIdx the value for relation.RELATED_POST_IDX
     *
     * @mbg.generated Wed Apr 11 19:49:13 KST 2018
     */
    public void setRelatedPostIdx(String relatedPostIdx) {
        this.relatedPostIdx = relatedPostIdx;
    }
}