package pe.oh29oh29.myweb.model;

public class Tag {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tags.IDX
	 * @mbg.generated  Tue May 01 00:53:15 KST 2018
	 */
	private String idx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tags.NAME
	 * @mbg.generated  Tue May 01 00:53:15 KST 2018
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tags.IDX
	 * @return  the value of tags.IDX
	 * @mbg.generated  Tue May 01 00:53:15 KST 2018
	 */
	public String getIdx() {
		return idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tags.IDX
	 * @param idx  the value for tags.IDX
	 * @mbg.generated  Tue May 01 00:53:15 KST 2018
	 */
	public void setIdx(String idx) {
		this.idx = idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tags.NAME
	 * @return  the value of tags.NAME
	 * @mbg.generated  Tue May 01 00:53:15 KST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tags.NAME
	 * @param name  the value for tags.NAME
	 * @mbg.generated  Tue May 01 00:53:15 KST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}
}