package pe.oh29oh29.myweb.model;

public class Tag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAGS.IDX
     *
     * @mbg.generated Mon Apr 30 22:29:24 KST 2018
     */
    private String idx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAGS.KEYWORD
     *
     * @mbg.generated Mon Apr 30 22:29:24 KST 2018
     */
    private String keyword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAGS.IDX
     *
     * @return the value of TAGS.IDX
     *
     * @mbg.generated Mon Apr 30 22:29:24 KST 2018
     */
    public String getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAGS.IDX
     *
     * @param idx the value for TAGS.IDX
     *
     * @mbg.generated Mon Apr 30 22:29:24 KST 2018
     */
    public void setIdx(String idx) {
        this.idx = idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAGS.KEYWORD
     *
     * @return the value of TAGS.KEYWORD
     *
     * @mbg.generated Mon Apr 30 22:29:24 KST 2018
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAGS.KEYWORD
     *
     * @param keyword the value for TAGS.KEYWORD
     *
     * @mbg.generated Mon Apr 30 22:29:24 KST 2018
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }
}