package pe.oh29oh29.myweb.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.oh29oh29.myweb.model.AttachedFile;
import pe.oh29oh29.myweb.model.AttachedFileExample;

public interface AttachedFileMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attached_files
	 * @mbg.generated  Tue May 15 18:02:04 KST 2018
	 */
	long countByExample(AttachedFileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attached_files
	 * @mbg.generated  Tue May 15 18:02:04 KST 2018
	 */
	int deleteByExample(AttachedFileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attached_files
	 * @mbg.generated  Tue May 15 18:02:04 KST 2018
	 */
	int deleteByPrimaryKey(String idx);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attached_files
	 * @mbg.generated  Tue May 15 18:02:04 KST 2018
	 */
	int insert(AttachedFile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attached_files
	 * @mbg.generated  Tue May 15 18:02:04 KST 2018
	 */
	int insertSelective(AttachedFile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attached_files
	 * @mbg.generated  Tue May 15 18:02:04 KST 2018
	 */
	List<AttachedFile> selectByExample(AttachedFileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attached_files
	 * @mbg.generated  Tue May 15 18:02:04 KST 2018
	 */
	AttachedFile selectByPrimaryKey(String idx);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attached_files
	 * @mbg.generated  Tue May 15 18:02:04 KST 2018
	 */
	int updateByExampleSelective(@Param("record") AttachedFile record, @Param("example") AttachedFileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attached_files
	 * @mbg.generated  Tue May 15 18:02:04 KST 2018
	 */
	int updateByExample(@Param("record") AttachedFile record, @Param("example") AttachedFileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attached_files
	 * @mbg.generated  Tue May 15 18:02:04 KST 2018
	 */
	int updateByPrimaryKeySelective(AttachedFile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attached_files
	 * @mbg.generated  Tue May 15 18:02:04 KST 2018
	 */
	int updateByPrimaryKey(AttachedFile record);
}