package pe.oh29oh29.myweb.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.oh29oh29.myweb.model.Category;
import pe.oh29oh29.myweb.model.CategoryExample;

public interface CategoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table categories
	 * @mbg.generated  Mon Apr 23 12:20:19 KST 2018
	 */
	long countByExample(CategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table categories
	 * @mbg.generated  Mon Apr 23 12:20:19 KST 2018
	 */
	int deleteByExample(CategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table categories
	 * @mbg.generated  Mon Apr 23 12:20:19 KST 2018
	 */
	int deleteByPrimaryKey(String idx);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table categories
	 * @mbg.generated  Mon Apr 23 12:20:19 KST 2018
	 */
	int insert(Category record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table categories
	 * @mbg.generated  Mon Apr 23 12:20:19 KST 2018
	 */
	int insertSelective(Category record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table categories
	 * @mbg.generated  Mon Apr 23 12:20:19 KST 2018
	 */
	List<Category> selectByExample(CategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table categories
	 * @mbg.generated  Mon Apr 23 12:20:19 KST 2018
	 */
	Category selectByPrimaryKey(String idx);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table categories
	 * @mbg.generated  Mon Apr 23 12:20:19 KST 2018
	 */
	int updateByExampleSelective(@Param("record") Category record, @Param("example") CategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table categories
	 * @mbg.generated  Mon Apr 23 12:20:19 KST 2018
	 */
	int updateByExample(@Param("record") Category record, @Param("example") CategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table categories
	 * @mbg.generated  Mon Apr 23 12:20:19 KST 2018
	 */
	int updateByPrimaryKeySelective(Category record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table categories
	 * @mbg.generated  Mon Apr 23 12:20:19 KST 2018
	 */
	int updateByPrimaryKey(Category record);
}