package pe.oh29oh29.myweb.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.oh29oh29.myweb.model.Comment;
import pe.oh29oh29.myweb.model.CommentExample;

public interface CommentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	long countByExample(CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	int deleteByExample(CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	int deleteByPrimaryKey(@Param("idx") String idx, @Param("postIdx") String postIdx,
			@Param("memberIdx") String memberIdx);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	int insert(Comment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	int insertSelective(Comment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	List<Comment> selectByExample(CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	Comment selectByPrimaryKey(@Param("idx") String idx, @Param("postIdx") String postIdx,
			@Param("memberIdx") String memberIdx);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	int updateByExampleSelective(@Param("record") Comment record, @Param("example") CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	int updateByExample(@Param("record") Comment record, @Param("example") CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	int updateByPrimaryKeySelective(Comment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	int updateByPrimaryKey(Comment record);
}