package pe.oh29oh29.myweb.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.oh29oh29.myweb.model.Members;
import pe.oh29oh29.myweb.model.MembersExample;

public interface MembersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEMBERS
	 * @mbg.generated  Wed Apr 04 16:57:34 KST 2018
	 */
	long countByExample(MembersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEMBERS
	 * @mbg.generated  Wed Apr 04 16:57:34 KST 2018
	 */
	int deleteByExample(MembersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEMBERS
	 * @mbg.generated  Wed Apr 04 16:57:34 KST 2018
	 */
	int deleteByPrimaryKey(String idx);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEMBERS
	 * @mbg.generated  Wed Apr 04 16:57:34 KST 2018
	 */
	int insert(Members record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEMBERS
	 * @mbg.generated  Wed Apr 04 16:57:34 KST 2018
	 */
	int insertSelective(Members record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEMBERS
	 * @mbg.generated  Wed Apr 04 16:57:34 KST 2018
	 */
	List<Members> selectByExample(MembersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEMBERS
	 * @mbg.generated  Wed Apr 04 16:57:34 KST 2018
	 */
	int updateByExampleSelective(@Param("record") Members record, @Param("example") MembersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEMBERS
	 * @mbg.generated  Wed Apr 04 16:57:34 KST 2018
	 */
	int updateByExample(@Param("record") Members record, @Param("example") MembersExample example);
}