package pe.oh29oh29.myweb.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.oh29oh29.myweb.model.Member;
import pe.oh29oh29.myweb.model.MemberExample;

public interface MemberMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members
	 * @mbg.generated  Wed Apr 11 19:49:13 KST 2018
	 */
	long countByExample(MemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members
	 * @mbg.generated  Wed Apr 11 19:49:13 KST 2018
	 */
	int deleteByExample(MemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members
	 * @mbg.generated  Wed Apr 11 19:49:13 KST 2018
	 */
	int deleteByPrimaryKey(String idx);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members
	 * @mbg.generated  Wed Apr 11 19:49:13 KST 2018
	 */
	int insert(Member record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members
	 * @mbg.generated  Wed Apr 11 19:49:13 KST 2018
	 */
	int insertSelective(Member record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members
	 * @mbg.generated  Wed Apr 11 19:49:13 KST 2018
	 */
	List<Member> selectByExample(MemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members
	 * @mbg.generated  Wed Apr 11 19:49:13 KST 2018
	 */
	Member selectByPrimaryKey(String idx);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members
	 * @mbg.generated  Wed Apr 11 19:49:13 KST 2018
	 */
	int updateByExampleSelective(@Param("record") Member record, @Param("example") MemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members
	 * @mbg.generated  Wed Apr 11 19:49:13 KST 2018
	 */
	int updateByExample(@Param("record") Member record, @Param("example") MemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members
	 * @mbg.generated  Wed Apr 11 19:49:13 KST 2018
	 */
	int updateByPrimaryKeySelective(Member record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members
	 * @mbg.generated  Wed Apr 11 19:49:13 KST 2018
	 */
	int updateByPrimaryKey(Member record);
}