package pe.oh29oh29.myweb.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.oh29oh29.myweb.model.PostCommentsExample;
import pe.oh29oh29.myweb.model.PostCommentsKey;
import pe.oh29oh29.myweb.model.PostComments;

public interface PostCommentsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_comments
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	long countByExample(PostCommentsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_comments
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	int deleteByExample(PostCommentsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_comments
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	int deleteByPrimaryKey(PostCommentsKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_comments
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	int insert(PostComments record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_comments
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	int insertSelective(PostComments record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_comments
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	List<PostComments> selectByExample(PostCommentsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_comments
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	PostComments selectByPrimaryKey(PostCommentsKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_comments
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	int updateByExampleSelective(@Param("record") PostComments record, @Param("example") PostCommentsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_comments
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	int updateByExample(@Param("record") PostComments record, @Param("example") PostCommentsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_comments
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	int updateByPrimaryKeySelective(PostComments record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_comments
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	int updateByPrimaryKey(PostComments record);
}