package pe.oh29oh29.myweb.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.oh29oh29.myweb.model.PostTagRelationExample;
import pe.oh29oh29.myweb.model.PostTagRelation;
import pe.oh29oh29.myweb.model.PostTagRelationKey;

public interface PostTagRelationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table POST_TAG_RELATIONS
	 * @mbg.generated  Wed May 02 16:52:57 KST 2018
	 */
	long countByExample(PostTagRelationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table POST_TAG_RELATIONS
	 * @mbg.generated  Wed May 02 16:52:57 KST 2018
	 */
	int deleteByExample(PostTagRelationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table POST_TAG_RELATIONS
	 * @mbg.generated  Wed May 02 16:52:57 KST 2018
	 */
	int deleteByPrimaryKey(PostTagRelationKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table POST_TAG_RELATIONS
	 * @mbg.generated  Wed May 02 16:52:57 KST 2018
	 */
	int insert(PostTagRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table POST_TAG_RELATIONS
	 * @mbg.generated  Wed May 02 16:52:57 KST 2018
	 */
	int insertSelective(PostTagRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table POST_TAG_RELATIONS
	 * @mbg.generated  Wed May 02 16:52:57 KST 2018
	 */
	List<PostTagRelation> selectByExample(PostTagRelationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table POST_TAG_RELATIONS
	 * @mbg.generated  Wed May 02 16:52:57 KST 2018
	 */
	PostTagRelation selectByPrimaryKey(PostTagRelationKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table POST_TAG_RELATIONS
	 * @mbg.generated  Wed May 02 16:52:57 KST 2018
	 */
	int updateByExampleSelective(@Param("record") PostTagRelation record,
			@Param("example") PostTagRelationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table POST_TAG_RELATIONS
	 * @mbg.generated  Wed May 02 16:52:57 KST 2018
	 */
	int updateByExample(@Param("record") PostTagRelation record, @Param("example") PostTagRelationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table POST_TAG_RELATIONS
	 * @mbg.generated  Wed May 02 16:52:57 KST 2018
	 */
	int updateByPrimaryKeySelective(PostTagRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table POST_TAG_RELATIONS
	 * @mbg.generated  Wed May 02 16:52:57 KST 2018
	 */
	int updateByPrimaryKey(PostTagRelation record);
}