package pe.oh29oh29.myweb.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.oh29oh29.myweb.model.PostsExample;
import pe.oh29oh29.myweb.model.PostsKey;

public interface PostsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Wed Apr 04 15:40:39 KST 2018
     */
    long countByExample(PostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Wed Apr 04 15:40:39 KST 2018
     */
    int deleteByExample(PostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Wed Apr 04 15:40:39 KST 2018
     */
    int deleteByPrimaryKey(PostsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Wed Apr 04 15:40:39 KST 2018
     */
    int insert(PostsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Wed Apr 04 15:40:39 KST 2018
     */
    int insertSelective(PostsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Wed Apr 04 15:40:39 KST 2018
     */
    List<PostsKey> selectByExample(PostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Wed Apr 04 15:40:39 KST 2018
     */
    int updateByExampleSelective(@Param("record") PostsKey record, @Param("example") PostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Wed Apr 04 15:40:39 KST 2018
     */
    int updateByExample(@Param("record") PostsKey record, @Param("example") PostsExample example);
}