package pe.oh29oh29.myweb.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.oh29oh29.myweb.model.PostTagRelationView;
import pe.oh29oh29.myweb.model.PostTagRelationViewExample;

public interface PostTagRelationViewMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_tag_relations_view
	 * @mbg.generated  Wed May 02 17:00:00 KST 2018
	 */
	long countByExample(PostTagRelationViewExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_tag_relations_view
	 * @mbg.generated  Wed May 02 17:00:00 KST 2018
	 */
	List<PostTagRelationView> selectByExample(PostTagRelationViewExample example);
}