package pe.oh29oh29.myweb.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.oh29oh29.myweb.model.PostsExample;
import pe.oh29oh29.myweb.model.PostsKey;
import pe.oh29oh29.myweb.model.Posts;

public interface PostsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	long countByExample(PostsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	int deleteByExample(PostsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	int deleteByPrimaryKey(PostsKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	int insert(Posts record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	int insertSelective(Posts record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	List<Posts> selectByExampleWithBLOBs(PostsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	List<Posts> selectByExample(PostsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	Posts selectByPrimaryKey(PostsKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	int updateByExampleSelective(@Param("record") Posts record, @Param("example") PostsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	int updateByExampleWithBLOBs(@Param("record") Posts record, @Param("example") PostsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	int updateByExample(@Param("record") Posts record, @Param("example") PostsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	int updateByPrimaryKeySelective(Posts record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	int updateByPrimaryKeyWithBLOBs(Posts record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts
	 * @mbg.generated  Sun Apr 08 23:39:31 KST 2018
	 */
	int updateByPrimaryKey(Posts record);
}