package pe.oh29oh29.myweb.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.oh29oh29.myweb.model.PostTagRelationExample;
import pe.oh29oh29.myweb.model.PostTagRelationKey;

public interface PostTagRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST_TAG_RELATIONS
     *
     * @mbg.generated Mon Apr 30 22:29:24 KST 2018
     */
    long countByExample(PostTagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST_TAG_RELATIONS
     *
     * @mbg.generated Mon Apr 30 22:29:24 KST 2018
     */
    int deleteByExample(PostTagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST_TAG_RELATIONS
     *
     * @mbg.generated Mon Apr 30 22:29:24 KST 2018
     */
    int deleteByPrimaryKey(PostTagRelationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST_TAG_RELATIONS
     *
     * @mbg.generated Mon Apr 30 22:29:24 KST 2018
     */
    int insert(PostTagRelationKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST_TAG_RELATIONS
     *
     * @mbg.generated Mon Apr 30 22:29:24 KST 2018
     */
    int insertSelective(PostTagRelationKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST_TAG_RELATIONS
     *
     * @mbg.generated Mon Apr 30 22:29:24 KST 2018
     */
    List<PostTagRelationKey> selectByExample(PostTagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST_TAG_RELATIONS
     *
     * @mbg.generated Mon Apr 30 22:29:24 KST 2018
     */
    int updateByExampleSelective(@Param("record") PostTagRelationKey record, @Param("example") PostTagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST_TAG_RELATIONS
     *
     * @mbg.generated Mon Apr 30 22:29:24 KST 2018
     */
    int updateByExample(@Param("record") PostTagRelationKey record, @Param("example") PostTagRelationExample example);
}