package pe.oh29oh29.myweb.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.oh29oh29.myweb.model.PostComment;
import pe.oh29oh29.myweb.model.PostCommentExample;
import pe.oh29oh29.myweb.model.PostCommentKey;

public interface PostCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST_COMMENTS
     *
     * @mbg.generated Tue Apr 10 19:37:22 KST 2018
     */
    long countByExample(PostCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST_COMMENTS
     *
     * @mbg.generated Tue Apr 10 19:37:22 KST 2018
     */
    int deleteByExample(PostCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST_COMMENTS
     *
     * @mbg.generated Tue Apr 10 19:37:22 KST 2018
     */
    int deleteByPrimaryKey(PostCommentKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST_COMMENTS
     *
     * @mbg.generated Tue Apr 10 19:37:22 KST 2018
     */
    int insert(PostComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST_COMMENTS
     *
     * @mbg.generated Tue Apr 10 19:37:22 KST 2018
     */
    int insertSelective(PostComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST_COMMENTS
     *
     * @mbg.generated Tue Apr 10 19:37:22 KST 2018
     */
    List<PostComment> selectByExample(PostCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST_COMMENTS
     *
     * @mbg.generated Tue Apr 10 19:37:22 KST 2018
     */
    PostComment selectByPrimaryKey(PostCommentKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST_COMMENTS
     *
     * @mbg.generated Tue Apr 10 19:37:22 KST 2018
     */
    int updateByExampleSelective(@Param("record") PostComment record, @Param("example") PostCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST_COMMENTS
     *
     * @mbg.generated Tue Apr 10 19:37:22 KST 2018
     */
    int updateByExample(@Param("record") PostComment record, @Param("example") PostCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST_COMMENTS
     *
     * @mbg.generated Tue Apr 10 19:37:22 KST 2018
     */
    int updateByPrimaryKeySelective(PostComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST_COMMENTS
     *
     * @mbg.generated Tue Apr 10 19:37:22 KST 2018
     */
    int updateByPrimaryKey(PostComment record);
}