package pe.oh29oh29.myweb.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.oh29oh29.myweb.model.PostTagRelationExample;
import pe.oh29oh29.myweb.model.PostTagRelation;

public interface PostTagRelationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_tag_relations
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	long countByExample(PostTagRelationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_tag_relations
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	int deleteByExample(PostTagRelationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_tag_relations
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	int deleteByPrimaryKey(@Param("postIdx") String postIdx, @Param("tagIdx") String tagIdx);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_tag_relations
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	int insert(PostTagRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_tag_relations
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	int insertSelective(PostTagRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_tag_relations
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	List<PostTagRelation> selectByExample(PostTagRelationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_tag_relations
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	int updateByExampleSelective(@Param("record") PostTagRelation record,
			@Param("example") PostTagRelationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_tag_relations
	 * @mbg.generated  Tue May 01 00:10:51 KST 2018
	 */
	int updateByExample(@Param("record") PostTagRelation record, @Param("example") PostTagRelationExample example);
}