package pe.oh29oh29.myweb.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.oh29oh29.myweb.model.RelationExample;
import pe.oh29oh29.myweb.model.RelationKey;

public interface RelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated Wed Apr 11 19:49:13 KST 2018
     */
    long countByExample(RelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated Wed Apr 11 19:49:13 KST 2018
     */
    int deleteByExample(RelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated Wed Apr 11 19:49:13 KST 2018
     */
    int deleteByPrimaryKey(RelationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated Wed Apr 11 19:49:13 KST 2018
     */
    int insert(RelationKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated Wed Apr 11 19:49:13 KST 2018
     */
    int insertSelective(RelationKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated Wed Apr 11 19:49:13 KST 2018
     */
    List<RelationKey> selectByExample(RelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated Wed Apr 11 19:49:13 KST 2018
     */
    int updateByExampleSelective(@Param("record") RelationKey record, @Param("example") RelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated Wed Apr 11 19:49:13 KST 2018
     */
    int updateByExample(@Param("record") RelationKey record, @Param("example") RelationExample example);
}