package pe.oh29oh29.myweb.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.oh29oh29.myweb.model.Tag;
import pe.oh29oh29.myweb.model.TagExample;

public interface TagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGS
     *
     * @mbg.generated Mon Apr 30 22:29:24 KST 2018
     */
    long countByExample(TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGS
     *
     * @mbg.generated Mon Apr 30 22:29:24 KST 2018
     */
    int deleteByExample(TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGS
     *
     * @mbg.generated Mon Apr 30 22:29:24 KST 2018
     */
    int deleteByPrimaryKey(String idx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGS
     *
     * @mbg.generated Mon Apr 30 22:29:24 KST 2018
     */
    int insert(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGS
     *
     * @mbg.generated Mon Apr 30 22:29:24 KST 2018
     */
    int insertSelective(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGS
     *
     * @mbg.generated Mon Apr 30 22:29:24 KST 2018
     */
    List<Tag> selectByExample(TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGS
     *
     * @mbg.generated Mon Apr 30 22:29:24 KST 2018
     */
    Tag selectByPrimaryKey(String idx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGS
     *
     * @mbg.generated Mon Apr 30 22:29:24 KST 2018
     */
    int updateByExampleSelective(@Param("record") Tag record, @Param("example") TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGS
     *
     * @mbg.generated Mon Apr 30 22:29:24 KST 2018
     */
    int updateByExample(@Param("record") Tag record, @Param("example") TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGS
     *
     * @mbg.generated Mon Apr 30 22:29:24 KST 2018
     */
    int updateByPrimaryKeySelective(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGS
     *
     * @mbg.generated Mon Apr 30 22:29:24 KST 2018
     */
    int updateByPrimaryKey(Tag record);
}